<?php

namespace Database\Seeders;

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CursoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        // ------------------------------------------------------------------------------
        DB::table('curso')->insert([
            'referencia' => '001400',
            'nome' => '5S - Ferramentas da Qualidade - Contínuo',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '002400',
            'nome' => 'Análise de Riscos',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '003100',
            'nome' => 'Atendimento Pré Hospitalar (Primeiros Socorros)',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 9,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Auxilie na capacitação básica de estudantes, profissionais de saúde e colaboradores interessados na área.',
            'descricao' =>   'Auxilie na capacitação básica de estudantes, profissionais de saúde e colaboradores interessados na área, a prestarem atendimento Pré-Hospitalar de Urgência e Emergência em uma plataforma 100% em conformidade com a NR 1.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '003200',
            'nome' => 'Atendimento Pré Hospitalar (Primeiros Socorros)',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Ofereça aos seus clientes treinamento em nível intermediário para a prestação de primeiros socorros.',
            'descricao' =>  'Ofereça aos seus clientes treinamento em nível intermediário para a prestação de primeiros socorros a pacientes com risco de vida, de forma extremamente fácil e intuitiva em uma plataforma 100% em conformidade com a NR 1.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '004400',
            'nome' => 'Avaliação Geral de Cena',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 1,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '005400',
            'nome' => 'Curso Online Complementar ao Treinamento Presencial NR13 - Segurança na Operação de Caldeiras',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Capacite o profissional que atua na operação e controle de caldeiras, conforme a norma regulamentadora',
            'descricao' =>  'Curso é destinado aos trabalhadores envolvidos, direta ou indiretamente, com a operação das instalações. O treinamento estabelece requisitos mínimos para gestão da integridade estrutural de caldeira a vapor, nos aspectos relacionados á instalação, a inspeção, a operação e manutenção, visando a segurança e à saúde dos trabalhadores.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '006400',
            'nome' => 'Curso Online Complementar ao Treinamento Presencial NR13 - Unidades de Processo',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Capacite seus trabalhadores que operam unidades de processo com vasos de pressão.',
            'descricao' =>  'Disponibilize aos seus clientes o melhor sistema de gestão de treinamentos SST. Inteligente e intuitivo, ele permite que os profissionais sejam capacitados com as melhores práticas de operação nas unidades de processo de acordo com a NR 13, e com tutores especialistas aptos para dar suporte aos alunos.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '007400',
            'nome' => 'Direção Defensiva para Motoristas de Caminhão',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Convide seus clientes a oferecerem um curso para motoristas sobre Direção defensiva.',
            'descricao'  => 'Convide seus clientes a oferecerem um curso para motoristas sobre Direção defensiva para que os profissionais conduzam seus veículos de forma segura e preventiva, tendo durante o curso o apoio de instrutores especialistas.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '008400',
            'nome' => 'Direção Preventiva para Froteiros',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Este treinamento capacitará froteiros para a condução segura dos veículos.',
            'descricao' =>  'Este treinamento capacitará froteiros para a condução segura dos veículos, ensinando-os a evitar comportamentos inadequados que podem causar acidentes no trânsito, com certificados emitidos automaticamente e válidos em todo o Brasil.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009300',
            'nome' => 'Formação Brigada de Incêndios - Conforme NBR14276',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   3,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Em 11 módulos completos que juntam teoria e prática.',
            'descricao'  => 'Em 11 módulos completos que juntam teoria e prática, leve qualidade a profissionais brigadistas e colaboradores para minimizar perdas e incidentes na empresa, afinal, acreditamos que trabalhadores seguros são trabalhadores motivados.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009310',
            'nome' => 'Formação Brigada de Incêndios - Conforme NBR14276',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   3,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Ajude empresas a reciclar seus colaboradores para atuar em suas brigadas internas e equipes de CIPA.',
            'descricao' => 'Ajude empresas a reciclar seus colaboradores para atuar em suas brigadas internas e equipes de CIPA, minimizando as perdas, preservando vidas, e resguardando o patrimônio da empresa, além disso, todos os nossos profissionais são comprometidos em entregar treinamentos de altíssima qualidade para o seu cliente.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009100',
            'nome' => 'Formação Brigada de Incêndios - Conforme NBR14276',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Trabalhamos com o conceito QSMS-RS e Sustentabilidade para ajudar seus clientes a capacitarem colaboradores.',
            'descricao' =>   'Trabalhamos com o conceito QSMS-RS e Sustentabilidade para ajudar seus clientes a capacitarem colaboradores que atuam nas brigadas internas e equipes de CIPA, com cursos de altíssima qualidade que promovem grande interação dos alunos com os conteúdos disponibilizados.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009110',
            'nome' => 'Formação Brigada de Incêndios - Conforme NBR14276',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Ofereça reciclagem básica aos profissionais das áreas de indústrias, hotéis, comércios, e empresas em geral.',
            'descricao' =>   'Ofereça reciclagem básica aos profissionais das áreas de indústrias, hotéis, comércios, e empresas em geral para atuarem em suas brigadas internas e equipes de CIPA. O curso aborda conteúdos relevantes que vão dar suporte correto para a atuação dos profissionais e tutores especializados na área.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009200',
            'nome' => 'Formação Brigada de Incêndios - Conforme NBR14276',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 6,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Ofereça soluções em capacitações profissionais dos setores da indústria, hotéis, comércios.',
            'descricao' =>   'Ofereça soluções em capacitações profissionais dos setores da indústria, hotéis, comércios, varejo e empresas em geral, para estarem aptos a agir em momentos de risco. O profissional conta com aulas práticas e teóricas ministradas por especialistas da área.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009210',
            'nome' => 'Formação Brigada de Incêndios - Conforme NBR14276',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Seus clientes podem reduzir custos com treinamentos obrigatórios, oferecemos turmas de todos os tamanhos.,
descricao',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009301',
            'nome' => 'Formação de Brigada de Incêndio - Conforme IT17 de SP',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   3,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009311',
            'nome' => 'Formação de Brigada de Incêndio - Conforme IT17 de SP',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   3,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Ajude empresas a reciclar seus colaboradores para atuar em suas brigadas internas e equipes de CIPA.',
            'descricao' =>  'Ajude empresas a reciclar seus colaboradores para atuar em suas brigadas internas e equipes de CIPA, minimizando as perdas, preservando vidas, e resguardando o patrimônio da empresa, além disso, todos os nossos profissionais são comprometidos em entregar treinamentos de altíssima qualidade para o seu cliente.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009101',
            'nome' => 'Formação de Brigada de Incêndio - Conforme IT17 de SP',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 5,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009111',
            'nome' => 'Formação de Brigada de Incêndio - Conforme IT17 de SP',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009201',
            'nome' => 'Formação de Brigada de Incêndio - Conforme IT17 de SP',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 5,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Seus clientes podem reduzir custos com treinamentos obrigatórios, oferecemos turmas de todos os tamanhos.',
            'descricao' =>   'Seus clientes podem reduzir custos com treinamentos obrigatórios, oferecemos turmas de todos os tamanhos, que se iniciam a qualquer momento, com o intuito de capacitar profissionais das mais diversas áreas a estarem aptos para ação durante o combate ao incêndio, conforme a Instrução técnica nº. 17/2014 - SP.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '009211',
            'nome' => 'Formação de Brigada de Incêndio - Conforme IT17 de SP',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '010400',
            'nome' => 'Jogo da Coleta Seletiva',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 1,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '011400',
            'nome' => 'Lei Geral de Proteção de Dados - LGPD',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '012400',
            'nome' => 'Noções Básicas de Anatomia',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 1,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Venha capacitar profissionais com os melhores instrutores especialistas em SST.',
            'descricao' =>   'Venha capacitar profissionais com os melhores instrutores especialistas em SST para conhecerem a anatomia do corpo humano, identificar órgãos, sistemas corporais e reportar lesões. A nossa plataforma de ensino online está disponível 24 horas por dia.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '013400',
            'nome' => 'NR1 - Disposições Gerais',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 1,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '014100',
            'nome' => 'NR10 - Segurança Elétrica',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'O treinamento NR10 Básico do é destinado aos profissionais que desejam atuar como eletricistas.',
            'descricao' =>   'Com certificação válida em todo o território nacional, capacite trabalhadores do setor elétrico a intervir em instalações com possíveis riscos, e a agir preventivamente de maneira excelente em conformidade com a NR 1.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '014410',
            'nome' => 'NR10 - Segurança Elétrica',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'O treinamento NR10 Básico do é destinado aos profissionais que desejam atuar como eletricistas.',
            'descricao' =>   'Auxilie seus clientes na reciclagem de profissionais para minimizar as perdas, otimizar os indicadores de afastamento aplicados à NR 10 e diminuir os afastamentos.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '015410',
            'nome' => 'NR10 - SEP (Sistema Elétrico de Potência)',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '015400',
            'nome' => 'NR10 - SEP (Sistema Elétrico de Potência)',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'O treinamento NR10 Segurança Elétrica SEP é destinado aos profissionais que desejam atuar como eletricistas.',
            'descricao' => 'Treine profissionais com metodologias de ensino reconhecidas internacionalmente. Ajude-os a observar a NR10 para que possam prevenir acidentes por meio de técnicas eficientes para o controle dos riscos e perigos elétricos envolvidos com o SEP.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '016400',
            'nome' => 'NR11 - Transporte Movimentação Armazenagem e Manuseio de Materiais',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Todos os trabalhadores envolvidos no transporte e movimentação com uso de empilhadeira.',
            'descricao' =>  'Ofereça aos seus clientes, capacitação de acordo com a NR11, com o intuito de conscientizar os trabalhadores sobre os riscos existentes na operação e a importância de seguir todas as normas, por meio das nossas soluções de treinamentos SST 100% digital.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '016410',
            'nome' => 'NR11 - Transporte Movimentação Armazenagem e Manuseio de Materiais',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Todos os trabalhadores envolvidos no transporte e movimentação com uso de empilhadeira.',
            'descricao' =>  'Reciclar profissionais para dominarem os conceitos básicos de segurança conforme a NR11, nos processos de levantamento, transporte e descargas, de forma manual ou com máquinas é essencial. E com os treinamentos do Sistema Escudo, seus clientes terão auxílio de instrutores com proficiência no assunto para sanar dúvidas relacionadas ao treinamento.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '017400',
            'nome' => 'NR12 - Segurança no Trabalho em Máquinas e Equipamentos',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Este treinamento é obrigatório para trabalhadores envolvidos na operação.',
            'descricao' => 'Auxilie empresas a dar treinamentos inteligentes em SST. Neste curso os profissionais aprenderão a fazer o correto manuseio de máquinas e equipamentos com os métodos em que se aplica a NR12. São 5 módulos completos entre teoria e prática.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '017410',
            'nome' => 'NR12 - Segurança no Trabalho em Máquinas e Equipamentos',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Este treinamento é obrigatório para trabalhadores envolvidos na operação, manutenção, inspeção ou intervenção de máquinas.',
            'descricao' =>   'Convide seus clientes a reciclarem seus profissionais com excelência para a operação durante o manuseio dos equipamentos e máquinas em conformidade com a NR12. Com aulas práticas e teóricas, a empresa pode treinar seus colaboradores com baixo custo e alta qualidade no ensino.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '018400',
            'nome' => 'NR17 - Ergonomia',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Treine profissionais em conformidade com a NR 17 e com as tecnologias educacionais mais modernas.',
            'descricao' =>   'Treine profissionais em conformidade com a NR 17 e com as tecnologias educacionais mais modernas. São 2 horas de habilitação para que eles possam trabalhar de forma a respeitar a ergonomia no ambiente de trabalho, evitando danos ao corpo e doenças decorrentes do ofício, como a LER e DORT.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '019400',
            'nome' => 'NR17 - Ergonomia para Operadores de Checkout',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '1 ano',
            'texto_curto' => 'Ajude seus clientes a capacitarem operadores de checkout.',
            'descricao' =>   'Ajude seus clientes a capacitarem operadores de checkout de acordo com as regras ergonômicas definidas no Anexo I da NR 17, através de uma plataforma digital, prática e 100% em conformidade com a legislação.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '020400',
            'nome' => 'NR17 - Levantamento e Transporte Manual de Carga',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Capacite profissionais acerca dos procedimentos obrigatórios básicos previstos na NR 17',
            'descricao' =>   'Capacite profissionais acerca dos procedimentos obrigatórios básicos previstos na NR 17 com treinamentos acessíveis, fáceis de manejar e intuitivos para o seu trabalhador.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '021400',
            'nome' => 'NR17 - Teleatendimento',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '6 meses',
            'texto_curto' => 'Ofereça soluções em treinamentos digitais para profissionais de teleatendimento.',
            'descricao' =>   'Ofereça soluções em treinamentos digitais para profissionais de teleatendimento ou telemarketing com as melhores práticas ergonômicas.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022301',
            'nome' => 'NR20 Avançado I',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   3,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'Capacite trabalhadores ao nível avançado em conformidade com a NR 20.',
            'descricao' =>   'Capacite trabalhadores em nível avançado em conformidade com a NR 20, para que eles possam cumprir integralmente as exigências legais.Todos os treinamentos são fáceis e intuitivos, estimulando o engajamento dos alunos.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022311',
            'nome' => 'NR20 Avançado I',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   3,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'Ofereça aos seus clientes treinamentos de reciclagem avançados para profissionais que trabalham com inflamáveis.',
            'descricao' =>   'Ofereça aos seus clientes treinamentos de reciclagem avançados para profissionais que trabalham com inflamáveis e combustíveis, em uma plataforma digital que oferece o apoio de instrutores especialista durante todo o período do curso.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022302',
            'nome' => 'NR20 Avançado II',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   3,
            'valor' =>   0.00,
            'validade' => '1 ano',
            'texto_curto' => 'Prepare profissionais em um nível avançado, de acordo com a NR 20.',
            'descricao' =>   'Prepare profissionais em um nível avançado, de acordo com a NR 20, para executar com segurança serviços que envolvem inflamáveis e combustíveis da maneira correta. São 6 módulos completos com ensino teórico e prático com os melhores tutores do Brasil.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022312',
            'nome' => 'NR20 Avançado II',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   3,
            'valor' =>   0.00,
            'validade' => '1 ano',
            'texto_curto' => 'Recicle colaboradores com um método de aprendizagem tecnológico, moderno.',
            'descricao' =>   'Recicle colaboradores com um método de aprendizagem tecnológico, moderno e de altíssima qualidade, para que eles possam cumprir as exigências da NR 20 durante o contato com inflamáveis e combustíveis, e garantir um certificado válido em todo o país.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022110',
            'nome' => 'NR20 Básico',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => '3 anos',
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022101',
            'nome' => 'NR20 Básico Classe I',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => '3 anos',
            'texto_curto' => 'Capacite de forma remota e semipresencial trabalhadores que realizam atividades em instalações classe I.',
            'descricao' =>   'Capacite de forma remota e semipresencial trabalhadores que realizam atividades em instalações classe I, para que mantenham os processos de segurança durante todo o horário de trabalho observando e prevenindo riscos, de acordo com a nova NR.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022102',
            'nome' => 'NR20 Básico Classe II',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 6,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => '3 anos',
            'texto_curto' => 'Com métodos modernos e tecnológicos de aprendizagem.',
            'descricao' =>   'Com métodos modernos e tecnológicos de aprendizagem, capacite profissionais para que cumpram exigências legais da NR 20 de forma intuitiva e em conformidade com a NR 1.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022103',
            'nome' => 'NR20 Básico Classe III',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   1,
            'valor' =>   0.00,
            'validade' => '3 anos',
            'texto_curto' => 'Capacite trabalhadores que lidam diretamente com instalações de classe III.',
            'descricao' =>   'Capacite trabalhadores que lidam diretamente com instalações de classe III em turmas que podem ser personalizadas de acordo com as necessidades do seu cliente e começar a qualquer momento.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '023400',
            'nome' => 'NR20 Iniciação sobre Inflamáveis e Combustíveis',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '023410',
            'nome' => 'NR20 Iniciação sobre Inflamáveis e Combustíveis',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 3,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022200',
            'nome' => 'NR20 Intermediário',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022210',
            'nome' => 'NR20 Intermediário',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022201',
            'nome' => 'NR20 Intermediário Classe I',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => '3 anos',
            'texto_curto' => 'Ajude seus clientes a capacitarem de forma remota colaboradores de instalações classe I.',
            'descricao' =>   'Ajude seus clientes a capacitarem de forma remota colaboradores de instalações classe I, de acordo com a NR 20, para que zelem pela segurança ao adentrarem nas áreas de extração, produção, armazenamento, transferência, manuseio e manipulação de inflamáveis.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022202',
            'nome' => 'NR20 Intermediário Classe II',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'Auxilie clientes a capacitarem trabalhadores em nível intermediário para lidarem com instalações classe II.',
            'descricao' =>   'Auxilie clientes a capacitarem trabalhadores em nível intermediário para lidarem com instalações classe II, mantendo as boas práticas de segurança da NR 20, em uma plataforma digital, intuitiva e 100% em conformidade com a NR 1.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022203',
            'nome' => 'NR20 Intermediário Classe III',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 6,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'Disponibilize treinamentos virtuais a trabalhadores sobre as boas práticas contidas na NR 20.',
            'descricao' =>   'Disponibilize treinamentos virtuais a trabalhadores sobre as boas práticas contidas na NR 20, com o uso de tecnologias educacionais modernas e eficientes para garantir a melhor experiência de aprendizagem para o aluno.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022214',
            'nome' => 'NR 20 Intermediário Classes I, II e III',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   2,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Qualifique profissionais com os melhores instrutores especialistas em SST para poderem lidar com instalações classes I, II e III.',
            'descricao' => 'Qualifique profissionais com os melhores instrutores especialistas em SST para que possam lidar com instalações classes I, II e III, em conformidade com a NR 20, aprendendo sobre as melhores práticas ao adentrar o local de manipulação de inflamáveis e líquidos.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022401',
            'nome' => 'NR20 Específico Classe I',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022402',
            'nome' => 'NR20 Específico Classe II',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '022403',
            'nome' => 'NR20 Específico Classe III',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '024400',
            'nome' => 'NR33 Supervisor',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '1 ano',
            'texto_curto' => 'Com esse treinamento, seus alunos aprenderão sobre a melhor forma de proteção e prevenção de acidentes.',
            'descricao' =>   'Com esse treinamento, seus alunos aprenderão sobre a melhor forma de proteção e prevenção de acidentes na entrada de espaços confinados, em uma plataforma digital, em conformidade com a NR 1 e com certificados válidos em todo país.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '024410',
            'nome' => 'NR33 Supervisor ',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '1 ano',
            'texto_curto' => 'Ajude empresas a reduzirem os custos com capacitações obrigatórias.',
            'descricao' =>   'Ajude empresas a reduzirem os custos com capacitações obrigatórias de profissionais para agirem de acordo com a NBR 14787. Conte com instrutores treinados para atuarem de forma presencial, semipresencial e EaD.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '025400',
            'nome' => 'NR33 Trabalhador e Vigia',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 6,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '1 ano',
            'texto_curto' => 'Ajude profissionais da área de segurança para agir proativamente na prevenção de acidentes.',
            'descricao' =>   'Ajude profissionais da área de segurança para agir proativamente na prevenção de acidentes, levando em consideração a NBR 14787, oferecendo uma plataforma digital, em conformidade com a NR 1 e com o apoio de tutores especialistas no assunto.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '025410',
            'nome' => 'NR33 Trabalhador e Vigia',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '1 ano',
            'texto_curto' => 'Reciclar profissionais e reduzir os custos de treinamento dos seus clientes.',
            'descricao' =>   'Reciclar profissionais e reduzir os custos de treinamento dos seus clientes? Com o Sistema Escudo você faz os dois, capacitando os trabalhadores de acordo com a NBR 14787, treinando de forma remota, em conformidade com a NR 1 e com certificados válidos em todo o Brasil.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '026400',
            'nome' => 'NR35 - Trabalho em Altura',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'Proporcione aos seus clientes treinamentos digitais, intuitivos e certificados.',
            'descricao' =>   'Proporcione aos seus clientes treinamentos digitais, intuitivos e certificados de acordo com a NR 35, na plataforma de treinamentos EaD SST mais completa do Brasil.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '027400',
            'nome' => 'NR35 - Trabalho em Altura - Supervisor',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Capacite de forma remota ou semipresencial supervisores para que inspecionem corretamente.',
            'descricao' =>   'Capacite de forma remota ou semipresencial supervisores para que inspecionem corretamente os equipamentos e as condições de trabalho em altura, em conformidade com a NR 35 e em salas de aula digitais que podem ser acessadas 24h por dia.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '027410',
            'nome' => 'NR35 - Trabalho em Altura - Supervisor',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => null,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '026410',
            'nome' => 'NR35 - Trabalho em Altura',
            'is_reciclagem' => 1,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => 'Que tal reciclar profissionais que trabalham em altura superior a 2 metros, de acordo com a NR35.',
            'descricao' =>   'Que tal reciclar profissionais que trabalham em altura superior a 2 metros, de acordo com a NR35, na primeira plataforma digital em conformidade com a NR 1 no Brasil? Com o Sistema Escudo você entrega treinamentos de ponta, apoio de instrutores especialistas e segurança jurídica aos seus clientes.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '028400',
            'nome' => 'NR5 - Cipa',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Identifique onde as NRs se aplicam e quem são os responsáveis pelo seu cumprimento.',
            'descricao' =>   'Quem não precisa de uma CIPA capacitada e pronta para atuar em conformidade com a NR 5 hoje em dia? Com o Sistema Escudo, seus clientes terão acesso a treinamentos intuitivos, digitais e dentro da lei, com certificação válida em todo o país.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '029400',
            'nome' => 'NR5 - CIPA - GRAU DE RISCO 1',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 8,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '030400',
            'nome' => 'NR5 - CIPA - GRAU DE RISCO 2',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '031400',
            'nome' => 'NR5 - CIPA - GRAU DE RISCO 3',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 6,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '032400',
            'nome' => 'NR5 - CIPA - GRAU DE RISCO 4',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '033400',
            'nome' => 'NR5 - Cipa Designado',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '034400',
            'nome' => 'NR5 - CIPA Trabalho Rural',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 1,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 0,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => '2 anos',
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '035400',
            'nome' => 'NR6 - EPIs e EPCs (Equipamentos de Proteção Individual e Coletiva)',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Trabalhadores expostos a riscos.',
            'descricao' =>   'Capacite profissionais para o combater os riscos na sua origem, e fazendo o melhor uso dos Equipamentos de Proteção Individual (EPIs). São 2 horas de treinamento interativos para garantir o engajamento do aluno.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '036400',
            'nome' => 'PPR - Programa de Proteção Respiratória',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 4,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'Promova a capacitação remota dos profissionais para poderem estar seguros durante o processo.',
            'descricao' =>   'Promova a capacitação remota dos profissionais para poderem estar seguros durante o processo em relação à guarda, limpeza e higienização dos respiradores, através de uma plataforma em conformidade com a NR, segura e intuitiva.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '037400',
            'nome' => 'Prevenção e Combate à COVID-19',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '038400',
            'nome' => 'Prevenção e Proteção Contra Incêndios',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 6,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '039400',
            'nome' => 'Ressuscitação Cardiopulmonar - (RCP)',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 3,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => "",
            'descricao' => "",
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
        DB::table('curso')->insert([
            'referencia' => '040400',
            'nome' => 'Treinamento de Valas e Escavações',
            'is_reciclagem' => 0,
            'pratica_obrigatoria' => 0,
            'carga_horaria_pratica' =>   null,
            'carga_horaria' => 2,
            'fk_idformato' => null,
            'fk_idnivel' =>   4,
            'valor' =>   0.00,
            'validade' => null,
            'texto_curto' => 'A segurança no exercício das atividades diárias dos colaboradores é indispensável para o seu cliente.',
            'descricao' =>   'Aplicas os princípios de segurança ao trabalhador com valas e escavações. Proteger a si mesmo e outros profissionais nos diferentes tipos de trabalhos em valas e escavações. Aumentar a segurança ao trabalhar em fundações cravadas e injetadas.',
            'video' => null,
            'thumbnail' => null,
            'fk_idscorm' => null,
        ]);
    }
}
